name: Ежедневные случайные коммиты (1-3 шт)

on:
  schedule:
    - cron: '0 0 * * *'   # Каждый день в 00:00 UTC
  workflow_dispatch:      # Можно запустить вручную для теста

jobs:
  random-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Настроить Git под твой аккаунт
        run: |
          git config --local user.email "zmosY@users.noreply.github.com"
          git config --local user.name "zmosY"

      - name: Сгенерировать случайное количество коммитов (1-3) и сделать их
        run: |
          # Генерируем случайное число от 1 до 3
          COMMITS_COUNT=$(( (RANDOM % 3) + 1 ))
          echo "🎲 Будет сделано $COMMITS_COUNT коммитов сегодня"

          for i in $(seq 1 $COMMITS_COUNT); do
            echo "➡️ Готовим коммит №$i..."

            # Генерируем уникальное имя файла
            FILENAME="commit-file-$(date +%Y%m%d)-$i-$(shuf -i 1000-9999 -n 1).txt"

            # Генерируем случайные символы с помощью Python (heredoc)
            python3 << END_PYTHON
import random
import string

chars = ''.join(random.choices(string.ascii_letters + string.digits, k=50))
with open('$FILENAME', 'w') as f:
    f.write(chars + '\\n')

print(f'✅ Файл {FILENAME} создан.')
END_PYTHON

            # Добавляем, коммитим и пушим
            git add "$FILENAME"
            git commit -m "📝 Коммит №$i из $COMMITS_COUNT: $(date +%Y-%m-%d)"
            git push

            echo "✅ Коммит №$i отправлен!"
            echo "-------------------"
          done

          echo "🎉 Всего сделано $COMMITS_COUNT коммитов за сегодня."
